services:
  # WebSocket Server + Static File Serving
  - type: web
    name: story-point-poker
    env: node
    region: singapore
    plan: free
    buildCommand: cd client && yarn install && yarn build && cd ../server && yarn install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
